version: "3.8"
services:
  postgres:
    image: postgres:13.1-alpine
    environment:
      POSTGRES_USER:  
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
  zookeeper:
    image: confluentinc/cp-zookeeper:4.1.1
    hostname: zookeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:4.1.1
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  dockerize:
    image: jwilder/dockerize
volumes:
  database: